fix lesson
silversbro/v-v-serebryakov pull request #2
Opened 2024-12-15 19:49 UTC by silversbro

2025-01-06 11:30 UTC, agneum requested changes
Спасибо за вариант решения.
Хорошая работа, однако есть существенные замечания, и не хватает новых юнит-тестов.
Возвращаю задачу на доработку

Прошу при создании Pull Request использовать шаблон (Подробнее в инструкции по сдаче ДЗ)

2025-01-06 11:30 UTC, agneum commented on hw02_unpack_string/go.mod
> +module github.com/silversbro/hw02_unpack_string
Название модуля должно содержать полный путь, включая название репозитория

2025-01-06 11:30 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	}
Предлагаю вернуть результат работы или ошибку без дополнительных действий. Клиент на вызывающей стороне решит, что делать с ошибкой. 
Возвращать `str` не имеет смысла, потому что `str` была передана в качестве аргумента в функцию, то есть у пользователя пакета эта строка уже есть.

2025-01-06 11:30 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	readyString, err := WriteString(runes, str)
В функцию передаётся одни и те же данные, но разных типов. Рекомендую выбрать какой-то один и работать с ним.

2025-01-06 11:30 UTC, agneum commented on hw02_unpack_string/unpack.go
> +				return "", ErrInvalidString
Не совсем понимаю, что проверяется. Есть ли пример строки, для которой срабатывает этот case?

2025-01-06 11:30 UTC, agneum commented on hw02_unpack_string/unpack.go
> +				builder.WriteString(revertVal)
Перезапись результата выглядит достаточно неоптимально. 
Рекомендовал бы анализировать текущую руну, запоминать предыдущую руну и добавлять символы только, когда есть уверенность, что они попадут в итоговый результат.

Кстати, обращение по индексу не сработает для многобайтовых символов (кириллица, эмоджи, иероглифы). Есть мнение, что в этих случаях код отрежет "половинку" символа.

2025-01-06 11:30 UTC, agneum commented on hw02_unpack_string/unpack_test.go
> +	//nolint:depguard
Рекомендовал бы настроить depguard-конфиг линтера, чтобы не добавлять inline-исключения при каждом импорте пакета

2025-01-06 11:30 UTC, agneum commented on hw02_unpack_string/unpack_test.go
Не хватает новых юнит-тестов

2025-01-11 08:34 UTC, silversbro commented on hw02_unpack_string/unpack.go
> +				return "", ErrInvalidString
проверяется что это число а не цифра

2025-01-11 09:00 UTC, silversbro commented on hw02_unpack_string/unpack.go
> +				return "", ErrInvalidString
переделал через regexp

2025-01-11 09:00 UTC, silversbro commented on hw02_unpack_string/unpack.go
> +				builder.WriteString(revertVal)
да есть такое многобайтовые символы ломаются

2025-01-11 13:43 UTC, agneum approved these changes
Спасибо за правки, хорошая работа
 Принято

2025-01-16 19:59 UTC, merged